import iphone11_promax from './img/iphone11_promax.jpeg'
import iphone12_promax from './img/iphone12_promax.jpeg'
import iphone13_promax from './img/iphone13_promax.jpeg'
import iphone13 from './img/iphone13.jpeg'
import iphonex from './img/iphonex.jpeg'

export const ProductsData = [
  {
    id: 1, item: 'iphone11 pro', price: 20, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'
  },
  {id: 2, item: 'tecno spark 7', price: 23, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 3, item: 'iPhone 7', price: 34, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 4, item: 'samsung a12', price: 30, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 5, item: 'iphone11', price: 43, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 6, item: 'infinix', price: 34, image: iphone13, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 7, item: 'samsung a75', price: 26, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 8, item: 'iphone11 pro', price: 63, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 9, item: 'Galaxy a12', price: 34, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 10, item: 'Infinix', price: 30, image: iphone13, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 11, item: 'Note 5', price: 23, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 12, item: 'iphone11 pro', price: 63, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 13, item: 'note 3', price: 99, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 14, item: 'infinix hot 9', price: 37, image: iphonex, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 15, item: 'iphone11 pro', price: 47, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 16, item: 'tecno ka7', price: 84, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 17, item: 'iphone 6', price: 29, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 18, item: 'iphone11 pro', price: 69, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 19, item: 'pouvior', price: 24, image: iphone13, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 20, item: 'iphone 11', price: 84, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 21, item: 'infinix hot5', price: 85, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 22, item: 'iphone11 pro', price: 30, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 23, item: 'Samsung', price: 43, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 24, item: 'infinix', price: 34, image: iphonex, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 25, item: 'iphone11 pro', price: 26, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 26, item: 'iphone 11', price: 63, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 27, item: 'iphone 8', price: 34, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 28, item: 'Tesla', price: 30, image: iphone13, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 29, item: 'iphone11 pro', price: 23, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 30, item: 'iphone 6', price: 63, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 31, item: 'tesla', price: 99, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 32, item: 'iphone11', price: 37, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 33, item: 'tecno a2', price: 47, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 34, item: 'iphone 7', price: 84, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 35, item: 'tesla', price: 29, image: iphonex, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 36, item: 'tesla 7', price: 67, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 37, item: 'itel', price: 24, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 38, item: 'tesla x', price: 84, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 39, item: 'samsung a22', price: 85, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 40, item: 'iphone11 pro', price: 30, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 41, item: 'Samsung', price: 43, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 42, item: 'infinix', price: 34, image: iphonex, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 43, item: 'samsung a22', price: 26, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 44, item: 'samsung a27', price: 63, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 45, item: 'iphone 14', price: 34, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 46, item: 'iphone x', price: 30, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 47, item: 'samsung a65', price: 23, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 48, item: 'samsung a70', price: 63, image: iphone13, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 49, item: 'iphone11 pro', price: 99, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 50, item: 'tesla', price: 37, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 51, item: 'infinix', price: 47, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 52, item: 'itel', price: 84, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 53, item: 'huwae', price: 29, image: iphonex, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 54, item: 'samsung s21', price: 67, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 55, item: 'samsung s17', price: 24, image: iphone13, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 56, item: 'samsung a22', price: 84, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 57, item: 'Tecno a2', price: 85, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 58, item: 'infinix 3pro', price: 63, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 59, item: 'huwae x3', price: 99, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 60, item: 'huwae n6', price: 37, image: iphonex, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 61, item: 'samsung s11', price: 47, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 62, item: 'samsung s20', price: 84, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 63, item: 'iphone 9', price: 29, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 64, item: 'itel cx', price: 67, image: iphone13, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 65, item: 'iphone11 pro', price: 24, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 66, item: 'huwae ex', price: 84, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 67, item: 'itel qs', price: 85, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 68, item: 'tecno s5', price: 30, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 69, item: 'Samsung', price: 43, image: iphonex, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 70, item: 'iphone11', price: 34, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 71, item: 'tecno go', price: 26, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 72, item: 'itel s4', price: 63, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 73, item: 'samsung s15', price: 34, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 74, item: 'iphone 6s', price: 30, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 75, item: 'iphone 7', price: 23, image: iphone13, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 76, item: 'iphone12', price: 63, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 77, item: 'samsung a82', price: 99, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 78, item: 'tecno a11', price: 37, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 79, item: 'iphone13', price: 47, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 80, item: 'infinix x2', price: 84, image: iphone12_promax , count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 81, item: 'tecno px', price: 29, image: iphonex, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 82, item: 'iphone ssmax', price: 67, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 83, item: 'huwae nss', price: 24, image: iphone13_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}, 
  {id: 84, item: 'iphone ssmax', price: 84, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 85, item: 'huwae nd2', price: 85, image: iphone12_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'},
  {id: 86, item: 'tecno pro x', price: 134, image: iphone11_promax, count: 0, inCart: false,
    details: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Qui quod a nemo eos ut dolore reiciendis consectetur, vero, distinctio commodi nulla illum explicabo voluptate sapiente? Obcaecati tenetur esse vero accusamus delectus! Ea dolorem aut possimus esse nihil ad, dolorum dolores.'}]